### ISSUE TITLE
Randomly generate solutions

### ISSUE THREAD

**Issue by R3Ked** [Blananas2/ktane-logicChess#1]
Currently, there are only eight possible situations that each have the same answer whenever they come up, which means it is possible to create an optimized manual to completely cheese this module. I suggest randomizing each situation so this cannot happen. For example, in West's situation, he could've forgotten to add one or used the first digit in the serial instead of the last, or in Rene's situation, the modules that she got on Mssngv Wls would be different.

**Comment by R3Ked** [comment]
Blananas, if a month goes without you responding to this issue at all, then I will make a simplified manual.

**Comment by Fartlicker777** [comment]
Take a look at this fucking clown: https://www.youtube.com/watch?v=naVLU5s-tcM

**Comment by R3Ked** [comment]
> Blananas, if a month goes without you responding to this issue at all, then I will make a simplified manual.

hey can i punch you
